package com.beyond.note5.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.beyond.note5.bean.Document;
import com.beyond.note5.bean.Note;
import com.beyond.note5.bean.Todo;

import com.beyond.note5.dao.DocumentDao;
import com.beyond.note5.dao.NoteDao;
import com.beyond.note5.dao.TodoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig documentDaoConfig;
    private final DaoConfig noteDaoConfig;
    private final DaoConfig todoDaoConfig;

    private final DocumentDao documentDao;
    private final NoteDao noteDao;
    private final TodoDao todoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        documentDaoConfig = daoConfigMap.get(DocumentDao.class).clone();
        documentDaoConfig.initIdentityScope(type);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        todoDaoConfig = daoConfigMap.get(TodoDao.class).clone();
        todoDaoConfig.initIdentityScope(type);

        documentDao = new DocumentDao(documentDaoConfig, this);
        noteDao = new NoteDao(noteDaoConfig, this);
        todoDao = new TodoDao(todoDaoConfig, this);

        registerDao(Document.class, documentDao);
        registerDao(Note.class, noteDao);
        registerDao(Todo.class, todoDao);
    }
    
    public void clear() {
        documentDaoConfig.clearIdentityScope();
        noteDaoConfig.clearIdentityScope();
        todoDaoConfig.clearIdentityScope();
    }

    public DocumentDao getDocumentDao() {
        return documentDao;
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public TodoDao getTodoDao() {
        return todoDao;
    }

}
