package com.beyond.note5.model.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.beyond.note5.bean.Attachment;
import com.beyond.note5.bean.Note;
import com.beyond.note5.bean.Reminder;
import com.beyond.note5.bean.Todo;
import com.beyond.note5.bean.Document;
import com.beyond.note5.bean.SyncInfo;

import com.beyond.note5.model.dao.AttachmentDao;
import com.beyond.note5.model.dao.NoteDao;
import com.beyond.note5.model.dao.ReminderDao;
import com.beyond.note5.model.dao.TodoDao;
import com.beyond.note5.model.dao.DocumentDao;
import com.beyond.note5.model.dao.SyncInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig attachmentDaoConfig;
    private final DaoConfig noteDaoConfig;
    private final DaoConfig reminderDaoConfig;
    private final DaoConfig todoDaoConfig;
    private final DaoConfig documentDaoConfig;
    private final DaoConfig syncInfoDaoConfig;

    private final AttachmentDao attachmentDao;
    private final NoteDao noteDao;
    private final ReminderDao reminderDao;
    private final TodoDao todoDao;
    private final DocumentDao documentDao;
    private final SyncInfoDao syncInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        attachmentDaoConfig = daoConfigMap.get(AttachmentDao.class).clone();
        attachmentDaoConfig.initIdentityScope(type);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        reminderDaoConfig = daoConfigMap.get(ReminderDao.class).clone();
        reminderDaoConfig.initIdentityScope(type);

        todoDaoConfig = daoConfigMap.get(TodoDao.class).clone();
        todoDaoConfig.initIdentityScope(type);

        documentDaoConfig = daoConfigMap.get(DocumentDao.class).clone();
        documentDaoConfig.initIdentityScope(type);

        syncInfoDaoConfig = daoConfigMap.get(SyncInfoDao.class).clone();
        syncInfoDaoConfig.initIdentityScope(type);

        attachmentDao = new AttachmentDao(attachmentDaoConfig, this);
        noteDao = new NoteDao(noteDaoConfig, this);
        reminderDao = new ReminderDao(reminderDaoConfig, this);
        todoDao = new TodoDao(todoDaoConfig, this);
        documentDao = new DocumentDao(documentDaoConfig, this);
        syncInfoDao = new SyncInfoDao(syncInfoDaoConfig, this);

        registerDao(Attachment.class, attachmentDao);
        registerDao(Note.class, noteDao);
        registerDao(Reminder.class, reminderDao);
        registerDao(Todo.class, todoDao);
        registerDao(Document.class, documentDao);
        registerDao(SyncInfo.class, syncInfoDao);
    }
    
    public void clear() {
        attachmentDaoConfig.clearIdentityScope();
        noteDaoConfig.clearIdentityScope();
        reminderDaoConfig.clearIdentityScope();
        todoDaoConfig.clearIdentityScope();
        documentDaoConfig.clearIdentityScope();
        syncInfoDaoConfig.clearIdentityScope();
    }

    public AttachmentDao getAttachmentDao() {
        return attachmentDao;
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public ReminderDao getReminderDao() {
        return reminderDao;
    }

    public TodoDao getTodoDao() {
        return todoDao;
    }

    public DocumentDao getDocumentDao() {
        return documentDao;
    }

    public SyncInfoDao getSyncInfoDao() {
        return syncInfoDao;
    }

}
