package com.beyond.note5.model.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.beyond.note5.bean.Account;
import com.beyond.note5.bean.Attachment;
import com.beyond.note5.bean.Document;
import com.beyond.note5.bean.Note;
import com.beyond.note5.bean.Reminder;
import com.beyond.note5.bean.Todo;
import com.beyond.note5.sync.model.bean.SyncInfo;
import com.beyond.note5.sync.model.bean.SyncLogInfo;
import com.beyond.note5.sync.model.bean.SyncStateInfo;

import com.beyond.note5.model.dao.AccountDao;
import com.beyond.note5.model.dao.AttachmentDao;
import com.beyond.note5.model.dao.DocumentDao;
import com.beyond.note5.model.dao.NoteDao;
import com.beyond.note5.model.dao.ReminderDao;
import com.beyond.note5.model.dao.TodoDao;
import com.beyond.note5.model.dao.SyncInfoDao;
import com.beyond.note5.model.dao.SyncLogInfoDao;
import com.beyond.note5.model.dao.SyncStateInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accountDaoConfig;
    private final DaoConfig attachmentDaoConfig;
    private final DaoConfig documentDaoConfig;
    private final DaoConfig noteDaoConfig;
    private final DaoConfig reminderDaoConfig;
    private final DaoConfig todoDaoConfig;
    private final DaoConfig syncInfoDaoConfig;
    private final DaoConfig syncLogInfoDaoConfig;
    private final DaoConfig syncStateInfoDaoConfig;

    private final AccountDao accountDao;
    private final AttachmentDao attachmentDao;
    private final DocumentDao documentDao;
    private final NoteDao noteDao;
    private final ReminderDao reminderDao;
    private final TodoDao todoDao;
    private final SyncInfoDao syncInfoDao;
    private final SyncLogInfoDao syncLogInfoDao;
    private final SyncStateInfoDao syncStateInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accountDaoConfig = daoConfigMap.get(AccountDao.class).clone();
        accountDaoConfig.initIdentityScope(type);

        attachmentDaoConfig = daoConfigMap.get(AttachmentDao.class).clone();
        attachmentDaoConfig.initIdentityScope(type);

        documentDaoConfig = daoConfigMap.get(DocumentDao.class).clone();
        documentDaoConfig.initIdentityScope(type);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        reminderDaoConfig = daoConfigMap.get(ReminderDao.class).clone();
        reminderDaoConfig.initIdentityScope(type);

        todoDaoConfig = daoConfigMap.get(TodoDao.class).clone();
        todoDaoConfig.initIdentityScope(type);

        syncInfoDaoConfig = daoConfigMap.get(SyncInfoDao.class).clone();
        syncInfoDaoConfig.initIdentityScope(type);

        syncLogInfoDaoConfig = daoConfigMap.get(SyncLogInfoDao.class).clone();
        syncLogInfoDaoConfig.initIdentityScope(type);

        syncStateInfoDaoConfig = daoConfigMap.get(SyncStateInfoDao.class).clone();
        syncStateInfoDaoConfig.initIdentityScope(type);

        accountDao = new AccountDao(accountDaoConfig, this);
        attachmentDao = new AttachmentDao(attachmentDaoConfig, this);
        documentDao = new DocumentDao(documentDaoConfig, this);
        noteDao = new NoteDao(noteDaoConfig, this);
        reminderDao = new ReminderDao(reminderDaoConfig, this);
        todoDao = new TodoDao(todoDaoConfig, this);
        syncInfoDao = new SyncInfoDao(syncInfoDaoConfig, this);
        syncLogInfoDao = new SyncLogInfoDao(syncLogInfoDaoConfig, this);
        syncStateInfoDao = new SyncStateInfoDao(syncStateInfoDaoConfig, this);

        registerDao(Account.class, accountDao);
        registerDao(Attachment.class, attachmentDao);
        registerDao(Document.class, documentDao);
        registerDao(Note.class, noteDao);
        registerDao(Reminder.class, reminderDao);
        registerDao(Todo.class, todoDao);
        registerDao(SyncInfo.class, syncInfoDao);
        registerDao(SyncLogInfo.class, syncLogInfoDao);
        registerDao(SyncStateInfo.class, syncStateInfoDao);
    }
    
    public void clear() {
        accountDaoConfig.clearIdentityScope();
        attachmentDaoConfig.clearIdentityScope();
        documentDaoConfig.clearIdentityScope();
        noteDaoConfig.clearIdentityScope();
        reminderDaoConfig.clearIdentityScope();
        todoDaoConfig.clearIdentityScope();
        syncInfoDaoConfig.clearIdentityScope();
        syncLogInfoDaoConfig.clearIdentityScope();
        syncStateInfoDaoConfig.clearIdentityScope();
    }

    public AccountDao getAccountDao() {
        return accountDao;
    }

    public AttachmentDao getAttachmentDao() {
        return attachmentDao;
    }

    public DocumentDao getDocumentDao() {
        return documentDao;
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public ReminderDao getReminderDao() {
        return reminderDao;
    }

    public TodoDao getTodoDao() {
        return todoDao;
    }

    public SyncInfoDao getSyncInfoDao() {
        return syncInfoDao;
    }

    public SyncLogInfoDao getSyncLogInfoDao() {
        return syncLogInfoDao;
    }

    public SyncStateInfoDao getSyncStateInfoDao() {
        return syncStateInfoDao;
    }

}
